In [1]:
import os

if False:
    # Set environment variables for TensorFlow GPU allocator and XLA options
    os.environ['TF_GPU_ALLOCATOR'] = 'cuda_malloc_async'
    os.environ['TF_XLA_FLAGS'] = '--tf_xla_auto_jit=off'
    os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'

In [2]:
import tensorflow as tf

# Print TensorFlow version
print(f"TensorFlow version: {tf.__version__}")

# Check if TensorFlow is built with CUDA support (GPU acceleration)
print(f"Built with CUDA: {tf.test.is_built_with_cuda()}")

# List the number of available GPU devices
print(f"GPUs: {len(tf.config.list_physical_devices('GPU'))}")

# Retrieve a list of all available GPU devices
gpus = tf.config.list_physical_devices('GPU')

if gpus:
    try:
        # Enable memory growth for each GPU to prevent TensorFlow from allocating all memory upfront
        for gpu in gpus:
            tf.config.experimental.set_memory_growth(gpu, True)
            print(f"Available physical GPU: {gpu}")
        print("Memory growth enabled for all GPUs...")
    except RuntimeError as e:
        # Memory growth must be set before GPUs are initialized, so catch any errors here
        print(f"Error setting memory growth: {e}")
else:
    print("No GPU devices found")

2025-07-05 22:05:16.032859: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-07-05 22:05:16.054337: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1751749516.071624 1207854 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1751749516.077210 1207854 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1751749516.094120 1207854 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1751749516.094180 1207854 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1751749516.094183 1207854 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1751749516.094184 1207854 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2025-07-05 22:05:16.100552: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

TensorFlow version: 2.19.0
Built with CUDA: True
GPUs: 1
Available physical GPU: PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')
Memory growth enabled for all GPUs...

In [3]:
# Import mixed precision utilities from Keras
from tensorflow.keras import mixed_precision

# Import LossScaleOptimizer to help with training stability when using mixed precision
from tensorflow.keras.mixed_precision import LossScaleOptimizer

# Define the mixed precision policy
policy = mixed_precision.Policy('float32')

# Apply the global mixed precision policy
mixed_precision.set_global_policy(policy)

# Print out the compute and variable data types for confirmation
print("Compute dtype:", policy.compute_dtype)
print("Variable dtype:", policy.variable_dtype)

Compute dtype: float32
Variable dtype: float32

In [4]:
# Import Adam optimiser from Keras
from tensorflow.keras.optimizers import Adam

# Keras backend utilities
from tensorflow.keras import backend as K

# Garbage collection to free memory
import gc

# For k-fold cross-validation splitting
from sklearn.model_selection import KFold

In [5]:
# Import image augmentation utilities
import Components.image_utils as image_utils

# Import custom loss functions and metrics for segmentation
from Components.segmentation_utils import Losses, Metrics

# Import U-Net model variants for segmentation
from Components.unet_models import ModifiedUNet, DoubleUNet

# Import custom optimiser
from Components.model_optimisers import HnAdam

In [6]:
from Components.definitions import *

# Print dataset and related paths to verify correct setup
print(f"Dataset path: {DATA_ROOT}")
print(f"Meta path: {Paths.metadata_csv}")
print(f"Mass training data path: {Paths.new_mass_train_csv}")
print(f"Mass test data path: {Paths.new_mass_test_csv}")
print(f"Mass train tensor path: {Paths.mass_train_tensor_dir}")
print(f"Mass test tensor path: {Paths.mass_test_tensor_dir}")

Dataset path: /mnt/c/Users/lejam/Desktop/CBIS-DDSM/manifest-1748122768688
Meta path: /mnt/c/Users/lejam/Desktop/CBIS-DDSM/manifest-1748122768688/metadata.csv
Mass training data path: /mnt/c/Users/lejam/Desktop/CBIS-DDSM/manifest-1748122768688/new_mass_case_description_train_set.csv
Mass test data path: /mnt/c/Users/lejam/Desktop/CBIS-DDSM/manifest-1748122768688/new_mass_case_description_test_set.csv
Mass train tensor path: /mnt/c/Users/lejam/Desktop/CBIS-DDSM/manifest-1748122768688/mass_tensor/train
Mass test tensor path: /mnt/c/Users/lejam/Desktop/CBIS-DDSM/manifest-1748122768688/mass_tensor/test

In [7]:
# Import standard libraries
import math
import numpy as np
import pandas as pd

# Data Processing

In [8]:
# Load the updated mass training and testing datasets from CSV files
new_mass_train = pd.read_csv(Paths.new_mass_train_csv)
new_mass_test = pd.read_csv(Paths.new_mass_test_csv)

In [9]:
# Print the shape of the training dataset (rows, columns)
print(new_mass_train.shape)

# Display the first two rows of the training dataset for a quick preview
new_mass_train.head(2)

(1318, 14)

,patient_id,breast_density,left or right breast,image view,abnormality id,abnormality type,mass shape,mass margins,assessment,pathology,subtlety,image file path,cropped image file path,ROI mask file path
0,P_00001,3,LEFT,CC,1,mass,IRREGULAR-ARCHITECTURAL_DISTORTION,SPICULATED,4,MALIGNANT,4,Mass-Training_P_00001_LEFT_CC/1.3.6.1.4.1.9590...,Mass-Training_P_00001_LEFT_CC_1/1.3.6.1.4.1.95...,Mass-Training_P_00001_LEFT_CC_1/1.3.6.1.4.1.95...
1,P_00001,3,LEFT,MLO,1,mass,IRREGULAR-ARCHITECTURAL_DISTORTION,SPICULATED,4,MALIGNANT,4,Mass-Training_P_00001_LEFT_MLO/1.3.6.1.4.1.959...,Mass-Training_P_00001_LEFT_MLO_1/1.3.6.1.4.1.9...,Mass-Training_P_00001_LEFT_MLO_1/1.3.6.1.4.1.9...

In [10]:
# Print the shape of the test dataset (rows, columns)
print(new_mass_test.shape)

# Display the first two rows of the test dataset for a quick preview
new_mass_test.head(2)

(378, 14)

,patient_id,breast_density,left or right breast,image view,abnormality id,abnormality type,mass shape,mass margins,assessment,pathology,subtlety,image file path,cropped image file path,ROI mask file path
0,P_00016,4,LEFT,CC,1,mass,IRREGULAR,SPICULATED,5,MALIGNANT,5,Mass-Test_P_00016_LEFT_CC/1.3.6.1.4.1.9590.100...,Mass-Test_P_00016_LEFT_CC_1/1.3.6.1.4.1.9590.1...,Mass-Test_P_00016_LEFT_CC_1/1.3.6.1.4.1.9590.1...
1,P_00016,4,LEFT,MLO,1,mass,IRREGULAR,SPICULATED,5,MALIGNANT,5,Mass-Test_P_00016_LEFT_MLO/1.3.6.1.4.1.9590.10...,Mass-Test_P_00016_LEFT_MLO_1/1.3.6.1.4.1.9590....,Mass-Test_P_00016_LEFT_MLO_1/1.3.6.1.4.1.9590....

### Use **Laplacian filters** and prepare the datasets in tensor format

In [11]:
# Flags to control whether to process training and test data
process_train = False
process_test = False

# Get the total number of rows in the training and test datasets
target_train_rows = new_mass_train.shape[0]
target_test_rows = new_mass_test.shape[0]

# Select all rows from each dataset as targets
target_mass_train = new_mass_train[: target_train_rows]
target_mass_test = new_mass_test[: target_test_rows]

In [12]:
train_images = None
if process_train:
    # If processing training data is enabled:
    # 1. Load images and masks from file paths, resizing them to the target size
    # 2. Create a TensorFlow dataset from these image-mask pairs
    train_images = tf.data.Dataset.from_tensor_slices((
        list(map(lambda x: image_utils.load_image(os.path.join(data_root,'CBIS-DDSM', x), TARGET_SIZE[:2]), target_mass_train['image file path'])),
        list(map(lambda x: image_utils.mask_image(os.path.join(data_root,'CBIS-DDSM', x), TARGET_SIZE[:2]), target_mass_train['ROI mask file path']))
    ))
    # Save the dataset to disk for later use
    tf.data.Dataset.save(train_images, Paths.mass_train_tensor_dir)
else:
    # If not processing, load the pre-saved dataset from disk
    train_images = tf.data.Dataset.load(Paths.mass_train_tensor_dir)
    
# Preview the shape of the first image and mask pair in the dataset
for x, y in train_images.take(1):
    print(f"train image shape: {x.shape}, {y.shape}")

train image shape: (128, 128, 3), (128, 128, 1)

I0000 00:00:1751749520.175044 1207854 gpu_device.cc:2019] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 5564 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3070 Ti Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6
2025-07-05 22:05:20.358225: I tensorflow/core/framework/local_rendezvous.cc:407] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence

In [13]:
test_images = None
if process_test:
    # If processing test data is enabled:
    # 1. Load images and masks from file paths, resizing to target size
    # 2. Create a TensorFlow dataset from these image-mask pairs
    test_images = tf.data.Dataset.from_tensor_slices((
        list(map(lambda x: image_utils.load_image(os.path.join(data_root,'CBIS-DDSM', x), TARGET_SIZE[:2]), target_mass_test['image file path'])),
        list(map(lambda x: image_utils.mask_image(os.path.join(data_root,'CBIS-DDSM', x), TARGET_SIZE[:2]), target_mass_test['ROI mask file path']))
    ))
    # Save the dataset for later use
    tf.data.Dataset.save(test_images, Paths.mass_test_tensor_dir)
else:
    # If not processing, load the previously saved test dataset
    test_images = tf.data.Dataset.load(Paths.mass_test_tensor_dir)

# Display the shape of the first image and mask pair from the test dataset
for x, y in test_images.take(1):
    print(f"test image shape: {x.shape}, {y.shape}")

test image shape: (128, 128, 3), (128, 128, 1)

2025-07-05 22:05:20.507969: I tensorflow/core/framework/local_rendezvous.cc:407] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence

In [14]:
# Concatenate train and test datasets into a single combined dataset
combined_dataset = train_images.concatenate(test_images)

# Print the shape of the first image and mask pair from the combined dataset
for x, y in combined_dataset.take(1):
    print(f"combined image shape: {x.shape}, {y.shape}")

combined image shape: (128, 128, 3), (128, 128, 1)

### Create training, validation, and test datasets

In [15]:
train_rows = len(train_images) # Total number of training images
test_rows = len(test_images) # Total number of test images

val_size = int(0.8 * test_rows) # 80% of test images used for validation
test_size = test_rows - val_size # Remaining 20% for final testing

print(f"Number of train_images: {train_rows}")
print(f"Number of test_images: {test_rows}")
print(f"Validation data size: {val_size}")
print(f"Test batch size: {test_size}")

BATCH_SIZE = 8
print(f"batch size: {BATCH_SIZE}")

Number of train_images: 1318
Number of test_images: 378
Validation data size: 302
Test batch size: 76
batch size: 8

In [16]:
# Prepare the training dataset batches
train_batches = (
    train_images
    .cache() # Cache dataset in memory to improve performance during training
    .shuffle(buffer_size=train_rows)  # Shuffle the entire training dataset for better randomness
    .batch(BATCH_SIZE) # Group data into batches of specified size
    .map(image_utils.Augment()) # Apply data augmentation to each batch
    .repeat() # Repeat dataset indefinitely (needed for multiple epochs)
    .prefetch(tf.data.AUTOTUNE) # Prefetch for optimal GPU/CPU usage
)

# Prepare the validation dataset batches
validation_batches = (
    test_images
    .take(val_size) # Take the first 'val_size' samples for validation
    .batch(BATCH_SIZE, drop_remainder=True)
)

# Prepare the test dataset batches
test_batches = (
    test_images
    .skip(val_size)
    .take(test_size)
    .batch(BATCH_SIZE)
)

# Model Training

In [17]:
NUM_EPOCHS = 100 # Number of epochs to train per fold
K_SPLIT = 10 # Number of folds for cross-validation

# EarlyStopping callback to halt training when validation Dice coefficient stops improving
earlystop = tf.keras.callbacks.EarlyStopping(
    monitor='val_dice_coef',
    patience=NUM_EPOCHS, # Number of epochs with no improvement after which training will be stopped.
    verbose=1, # Mode 1 displays messages when the callback takes an action.
    restore_best_weights=True,
    mode='max' # 'max' mode since higher Dice coefficient is better
)

# Reduce learning rate when a metric has stopped improving
reduce_lr = tf.keras.callbacks.ReduceLROnPlateau(
    monitor='val_dice_coef',
    factor=0.9, # Factor by which the learning rate will be reduced. new_lr = lr * factor
    patience=10, # Number of epochs with no improvement after which learning rate will be reduced.
    verbose=1, # 1: update messages.
    mode='max', # In 'max' mode it will be reduced when the quantity monitored has stopped increasing.
    min_lr=1e-4 # Lower bound on the learning rate.
)

checkpoint_cb = tf.keras.callbacks.ModelCheckpoint(
    filepath=os.path.join(DATA_ROOT, 'best_mass_model.keras'),
    monitor="val_dice_coef",
    save_best_only=True, # Save only when val_dice_coef improves
    save_weights_only=False, # Save entire model
    mode="max",
    verbose=1
)

callbacks=[checkpoint_cb]

In [18]:
# Initialise the model (ModifiedUNet) with the specified input shape
model = ModifiedUNet(input_shape=TARGET_SIZE)
#model = DoubleUNet(input_shape=TARGET_SIZE)

# Create the optimiser
opt = LossScaleOptimizer(HnAdam(learning_rate=1e-4))
#opt = LossScaleOptimizer(tf.keras.optimizers.Adam(learning_rate=1e-5))

# Compile the model
model.compile(
    optimizer=opt,
    loss=Losses.combined_loss, # Loss function to minimise during training
    metrics=["accuracy", Metrics.dice_coef, Metrics.jaccard_index],
    jit_compile=True # Enable XLA JIT compilation for potential speed-up
)

# Store training history objects from each fold
history = []

# Convert the combined TensorFlow dataset into numpy arrays for easy indexing in k-fold
data_list = list(combined_dataset)
X_all = np.array([x[0].numpy() for x in data_list])
Y_all = np.array([x[1].numpy() for x in data_list])

# Initialise KFold cross-validator
kf = KFold(n_splits=K_SPLIT, shuffle=True, random_state=42)
dice_scores = []

# Clear any previous TF/Keras session and collect garbage to free memory
K.clear_session()
gc.collect()

# Outer loop: run the k-fold cross-validation process multiple times
# Inner loop: for each fold split of the dataset
for train_idx, val_idx in kf.split(X_all):
    # Split the data into training and validation sets based on current fold indices
    X_train, Y_train = X_all[train_idx], Y_all[train_idx]
    X_val, Y_val = X_all[val_idx], Y_all[val_idx]

    # Convert training and validation numpy arrays back to TensorFlow datasets
    train_ds = tf.data.Dataset.from_tensor_slices((X_train, Y_train)).batch(BATCH_SIZE).repeat().prefetch(tf.data.AUTOTUNE)
    val_ds = tf.data.Dataset.from_tensor_slices((X_val, Y_val)).batch(BATCH_SIZE)

    # Calculate how many batches per epoch for training and validation
    steps_per_epoch = math.ceil(len(X_train) / BATCH_SIZE)
    validation_steps = math.ceil(len(X_val) / BATCH_SIZE)

    # Train the model on the current fold dataset
    hist = model.fit(
        train_ds,
        validation_data=val_ds,
        epochs=NUM_EPOCHS,
        steps_per_epoch=steps_per_epoch,
        validation_steps=validation_steps,
        callbacks=callbacks
    )

    # Save training history for later analysis
    history.append(hist)

    # Evaluate the trained model on the validation set of the current fold
    results = model.evaluate(val_ds, steps=validation_steps)
    dice_scores.append(results[2])

    # Print current fold's Dice score and running mean Dice score
    print(f"Dice score: {results[2]:.4f}, Mean: {np.mean(dice_scores):.4f}")

2025-07-05 22:05:29.231448: I tensorflow/core/framework/local_rendezvous.cc:407] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence

Epoch 1/100

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1751749535.848032 1208122 service.cc:152] XLA service 0x791738029560 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
I0000 00:00:1751749535.848156 1208122 service.cc:160]   StreamExecutor device (0): NVIDIA GeForce RTX 3070 Ti Laptop GPU, Compute Capability 8.6
2025-07-05 22:05:35.926883: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:269] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
I0000 00:00:1751749537.002645 1208122 cuda_dnn.cc:529] Loaded cuDNN version 91002
2025-07-05 22:05:39.180619: W external/local_xla/xla/tsl/framework/bfc_allocator.cc:382] Garbage collection: deallocate free memory regions (i.e., allocations) so that we can re-allocate a larger region to avoid OOM due to memory fragmentation. If you see this message frequently, you are running near the threshold of the available device memory and re-allocation may incur great performance overhead. You may try smaller batch sizes to observe the performance impact. Set TF_ENABLE_GPU_GARBAGE_COLLECTION=false if you'd like to disable this feature.
2025-07-05 22:05:40.513371: W external/local_xla/xla/tsl/framework/bfc_allocator.cc:310] Allocator (GPU_0_bfc) ran out of memory trying to allocate 4.55GiB with freed_by_count=0. The caller indicates that this is not a failure, but this may mean that there could be performance gains if more memory were available.
I0000 00:00:1751749551.463023 1208122 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.

190/191 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.9544 - dice_coef: 0.0013 - jaccard_index: 6.5598e-04 - loss: 0.5727

2025-07-05 22:06:10.081561: E external/local_xla/xla/stream_executor/cuda/cuda_timer.cc:86] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
2025-07-05 22:06:10.322653: E external/local_xla/xla/stream_executor/cuda/cuda_timer.cc:86] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
2025-07-05 22:06:10.755986: W external/local_xla/xla/tsl/framework/bfc_allocator.cc:310] Allocator (GPU_0_bfc) ran out of memory trying to allocate 4.42GiB with freed_by_count=0. The caller indicates that this is not a failure, but this may mean that there could be performance gains if more memory were available.

191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step - accuracy: 0.9546 - dice_coef: 0.0013 - jaccard_index: 6.6269e-04 - loss: 0.5724

2025-07-05 22:06:23.091325: W external/local_xla/xla/tsl/framework/bfc_allocator.cc:310] Allocator (GPU_0_bfc) ran out of memory trying to allocate 4.55GiB with freed_by_count=0. The caller indicates that this is not a failure, but this may mean that there could be performance gains if more memory were available.
2025-07-05 22:06:26.084092: E external/local_xla/xla/stream_executor/cuda/cuda_timer.cc:86] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
2025-07-05 22:06:26.326551: E external/local_xla/xla/stream_executor/cuda/cuda_timer.cc:86] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.

Epoch 1: val_dice_coef improved from -inf to 0.00309, saving model to /mnt/c/Users/lejam/Desktop/CBIS-DDSM/manifest-1748122768688/best_mass_model.keras
191/191 ━━━━━━━━━━━━━━━━━━━━ 60s 205ms/step - accuracy: 0.9547 - dice_coef: 0.0013 - jaccard_index: 6.6934e-04 - loss: 0.5722 - val_accuracy: 0.9947 - val_dice_coef: 0.0031 - val_jaccard_index: 0.0016 - val_loss: 0.4948
Epoch 2/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - accuracy: 0.9908 - dice_coef: 0.0708 - jaccard_index: 0.0401 - loss: 0.4859
Epoch 2: val_dice_coef improved from 0.00309 to 0.10268, saving model to /mnt/c/Users/lejam/Desktop/CBIS-DDSM/manifest-1748122768688/best_mass_model.keras
191/191 ━━━━━━━━━━━━━━━━━━━━ 24s 124ms/step - accuracy: 0.9908 - dice_coef: 0.0712 - jaccard_index: 0.0403 - loss: 0.4858 - val_accuracy: 0.9948 - val_dice_coef: 0.1027 - val_jaccard_index: 0.0568 - val_loss: 0.4876
Epoch 3/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.9912 - dice_coef: 0.1742 - jaccard_index: 0.1049 - loss: 0.4542
Epoch 3: val_dice_coef improved from 0.10268 to 0.34240, saving model to /mnt/c/Users/lejam/Desktop/CBIS-DDSM/manifest-1748122768688/best_mass_model.keras
191/191 ━━━━━━━━━━━━━━━━━━━━ 22s 115ms/step - accuracy: 0.9912 - dice_coef: 0.1745 - jaccard_index: 0.1051 - loss: 0.4540 - val_accuracy: 0.9938 - val_dice_coef: 0.3424 - val_jaccard_index: 0.2157 - val_loss: 0.3484
Epoch 4/100
175/191 ━━━━━━━━━━━━━━━━━━━━ 1s 91ms/step - accuracy: 0.9920 - dice_coef: 0.2931 - jaccard_index: 0.1810 - loss: 0.3796
Epoch 4: val_dice_coef did not improve from 0.34240
191/191 ━━━━━━━━━━━━━━━━━━━━ 16s 81ms/step - accuracy: 0.9920 - dice_coef: 0.2943 - jaccard_index: 0.1819 - loss: 0.3792 - val_accuracy: 0.9903 - val_dice_coef: 0.3118 - val_jaccard_index: 0.1904 - val_loss: 0.3703
Epoch 5/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.9923 - dice_coef: 0.3080 - jaccard_index: 0.1930 - loss: 0.3729
Epoch 5: val_dice_coef did not improve from 0.34240
191/191 ━━━━━━━━━━━━━━━━━━━━ 18s 94ms/step - accuracy: 0.9923 - dice_coef: 0.3082 - jaccard_index: 0.1932 - loss: 0.3728 - val_accuracy: 0.9872 - val_dice_coef: 0.3124 - val_jaccard_index: 0.1908 - val_loss: 0.3717
Epoch 6/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.9930 - dice_coef: 0.3423 - jaccard_index: 0.2179 - loss: 0.3549
Epoch 6: val_dice_coef improved from 0.34240 to 0.37774, saving model to /mnt/c/Users/lejam/Desktop/CBIS-DDSM/manifest-1748122768688/best_mass_model.keras
191/191 ━━━━━━━━━━━━━━━━━━━━ 20s 105ms/step - accuracy: 0.9930 - dice_coef: 0.3424 - jaccard_index: 0.2180 - loss: 0.3548 - val_accuracy: 0.9925 - val_dice_coef: 0.3777 - val_jaccard_index: 0.2409 - val_loss: 0.3290
Epoch 7/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.9938 - dice_coef: 0.3876 - jaccard_index: 0.2532 - loss: 0.3298
Epoch 7: val_dice_coef improved from 0.37774 to 0.41887, saving model to /mnt/c/Users/lejam/Desktop/CBIS-DDSM/manifest-1748122768688/best_mass_model.keras
191/191 ━━━━━━━━━━━━━━━━━━━━ 20s 107ms/step - accuracy: 0.9938 - dice_coef: 0.3877 - jaccard_index: 0.2532 - loss: 0.3298 - val_accuracy: 0.9940 - val_dice_coef: 0.4189 - val_jaccard_index: 0.2765 - val_loss: 0.3067
Epoch 8/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - accuracy: 0.9937 - dice_coef: 0.3903 - jaccard_index: 0.2570 - loss: 0.3280
Epoch 8: val_dice_coef did not improve from 0.41887
191/191 ━━━━━━━━━━━━━━━━━━━━ 18s 93ms/step - accuracy: 0.9937 - dice_coef: 0.3904 - jaccard_index: 0.2570 - loss: 0.3279 - val_accuracy: 0.9950 - val_dice_coef: 0.3757 - val_jaccard_index: 0.2461 - val_loss: 0.3338
Epoch 9/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 0.9942 - dice_coef: 0.4121 - jaccard_index: 0.2754 - loss: 0.3170
Epoch 9: val_dice_coef did not improve from 0.41887
191/191 ━━━━━━━━━━━━━━━━━━━━ 16s 82ms/step - accuracy: 0.9942 - dice_coef: 0.4122 - jaccard_index: 0.2754 - loss: 0.3170 - val_accuracy: 0.9949 - val_dice_coef: 0.3775 - val_jaccard_index: 0.2464 - val_loss: 0.3322
Epoch 10/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 0.9945 - dice_coef: 0.4203 - jaccard_index: 0.2817 - loss: 0.3127
Epoch 10: val_dice_coef improved from 0.41887 to 0.43234, saving model to /mnt/c/Users/lejam/Desktop/CBIS-DDSM/manifest-1748122768688/best_mass_model.keras
191/191 ━━━━━━━━━━━━━━━━━━━━ 24s 127ms/step - accuracy: 0.9945 - dice_coef: 0.4205 - jaccard_index: 0.2819 - loss: 0.3127 - val_accuracy: 0.9938 - val_dice_coef: 0.4323 - val_jaccard_index: 0.2890 - val_loss: 0.3027
Epoch 11/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 0.9948 - dice_coef: 0.4494 - jaccard_index: 0.3059 - loss: 0.2962
Epoch 11: val_dice_coef did not improve from 0.43234
191/191 ━━━━━━━━━━━━━━━━━━━━ 16s 82ms/step - accuracy: 0.9948 - dice_coef: 0.4494 - jaccard_index: 0.3059 - loss: 0.2962 - val_accuracy: 0.9948 - val_dice_coef: 0.4146 - val_jaccard_index: 0.2730 - val_loss: 0.3094
Epoch 12/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 0.9948 - dice_coef: 0.4563 - jaccard_index: 0.3111 - loss: 0.2928
Epoch 12: val_dice_coef did not improve from 0.43234
191/191 ━━━━━━━━━━━━━━━━━━━━ 16s 82ms/step - accuracy: 0.9948 - dice_coef: 0.4564 - jaccard_index: 0.3111 - loss: 0.2928 - val_accuracy: 0.9938 - val_dice_coef: 0.3992 - val_jaccard_index: 0.2627 - val_loss: 0.3182
Epoch 13/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 0.9949 - dice_coef: 0.4671 - jaccard_index: 0.3219 - loss: 0.2875
Epoch 13: val_dice_coef did not improve from 0.43234
191/191 ━━━━━━━━━━━━━━━━━━━━ 18s 97ms/step - accuracy: 0.9949 - dice_coef: 0.4672 - jaccard_index: 0.3219 - loss: 0.2875 - val_accuracy: 0.9948 - val_dice_coef: 0.3872 - val_jaccard_index: 0.2570 - val_loss: 0.3281
Epoch 14/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.9954 - dice_coef: 0.4946 - jaccard_index: 0.3465 - loss: 0.2732
Epoch 14: val_dice_coef did not improve from 0.43234
191/191 ━━━━━━━━━━━━━━━━━━━━ 16s 83ms/step - accuracy: 0.9954 - dice_coef: 0.4947 - jaccard_index: 0.3465 - loss: 0.2731 - val_accuracy: 0.9948 - val_dice_coef: 0.4183 - val_jaccard_index: 0.2849 - val_loss: 0.3118
Epoch 15/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.9954 - dice_coef: 0.5003 - jaccard_index: 0.3510 - loss: 0.2694
Epoch 15: val_dice_coef did not improve from 0.43234
191/191 ━━━━━━━━━━━━━━━━━━━━ 18s 97ms/step - accuracy: 0.9954 - dice_coef: 0.5003 - jaccard_index: 0.3510 - loss: 0.2694 - val_accuracy: 0.9923 - val_dice_coef: 0.3667 - val_jaccard_index: 0.2423 - val_loss: 0.3377
Epoch 16/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.9951 - dice_coef: 0.4790 - jaccard_index: 0.3332 - loss: 0.2804
Epoch 16: val_dice_coef did not improve from 0.43234
191/191 ━━━━━━━━━━━━━━━━━━━━ 16s 81ms/step - accuracy: 0.9951 - dice_coef: 0.4792 - jaccard_index: 0.3333 - loss: 0.2803 - val_accuracy: 0.9943 - val_dice_coef: 0.4237 - val_jaccard_index: 0.2894 - val_loss: 0.3077
Epoch 17/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.9957 - dice_coef: 0.5219 - jaccard_index: 0.3711 - loss: 0.2568
Epoch 17: val_dice_coef did not improve from 0.43234
191/191 ━━━━━━━━━━━━━━━━━━━━ 18s 94ms/step - accuracy: 0.9957 - dice_coef: 0.5219 - jaccard_index: 0.3711 - loss: 0.2568 - val_accuracy: 0.9948 - val_dice_coef: 0.3898 - val_jaccard_index: 0.2602 - val_loss: 0.3273
Epoch 18/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.9955 - dice_coef: 0.5214 - jaccard_index: 0.3702 - loss: 0.2579
Epoch 18: val_dice_coef did not improve from 0.43234
191/191 ━━━━━━━━━━━━━━━━━━━━ 16s 82ms/step - accuracy: 0.9955 - dice_coef: 0.5215 - jaccard_index: 0.3703 - loss: 0.2578 - val_accuracy: 0.9942 - val_dice_coef: 0.4207 - val_jaccard_index: 0.2826 - val_loss: 0.3118
Epoch 19/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.9958 - dice_coef: 0.5313 - jaccard_index: 0.3790 - loss: 0.2521
Epoch 19: val_dice_coef did not improve from 0.43234
191/191 ━━━━━━━━━━━━━━━━━━━━ 18s 94ms/step - accuracy: 0.9958 - dice_coef: 0.5314 - jaccard_index: 0.3790 - loss: 0.2520 - val_accuracy: 0.9947 - val_dice_coef: 0.4257 - val_jaccard_index: 0.2873 - val_loss: 0.3048
Epoch 20/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.9958 - dice_coef: 0.5247 - jaccard_index: 0.3728 - loss: 0.2555
Epoch 20: val_dice_coef improved from 0.43234 to 0.43285, saving model to /mnt/c/Users/lejam/Desktop/CBIS-DDSM/manifest-1748122768688/best_mass_model.keras
191/191 ━━━━━━━━━━━━━━━━━━━━ 21s 109ms/step - accuracy: 0.9958 - dice_coef: 0.5248 - jaccard_index: 0.3729 - loss: 0.2554 - val_accuracy: 0.9940 - val_dice_coef: 0.4328 - val_jaccard_index: 0.2967 - val_loss: 0.3057
Epoch 21/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 0.9961 - dice_coef: 0.5628 - jaccard_index: 0.4100 - loss: 0.2354
Epoch 21: val_dice_coef did not improve from 0.43285
191/191 ━━━━━━━━━━━━━━━━━━━━ 16s 81ms/step - accuracy: 0.9961 - dice_coef: 0.5629 - jaccard_index: 0.4100 - loss: 0.2353 - val_accuracy: 0.9943 - val_dice_coef: 0.4042 - val_jaccard_index: 0.2714 - val_loss: 0.3190
Epoch 22/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.9962 - dice_coef: 0.5697 - jaccard_index: 0.4149 - loss: 0.2323
Epoch 22: val_dice_coef did not improve from 0.43285
191/191 ━━━━━━━━━━━━━━━━━━━━ 18s 94ms/step - accuracy: 0.9962 - dice_coef: 0.5697 - jaccard_index: 0.4149 - loss: 0.2323 - val_accuracy: 0.9944 - val_dice_coef: 0.3881 - val_jaccard_index: 0.2617 - val_loss: 0.3282
Epoch 23/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 0.9961 - dice_coef: 0.5666 - jaccard_index: 0.4144 - loss: 0.2333
Epoch 23: val_dice_coef did not improve from 0.43285
191/191 ━━━━━━━━━━━━━━━━━━━━ 16s 82ms/step - accuracy: 0.9961 - dice_coef: 0.5666 - jaccard_index: 0.4145 - loss: 0.2333 - val_accuracy: 0.9949 - val_dice_coef: 0.4142 - val_jaccard_index: 0.2843 - val_loss: 0.3117
Epoch 24/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 0.9965 - dice_coef: 0.5970 - jaccard_index: 0.4439 - loss: 0.2167
Epoch 24: val_dice_coef did not improve from 0.43285
191/191 ━━━━━━━━━━━━━━━━━━━━ 18s 95ms/step - accuracy: 0.9965 - dice_coef: 0.5970 - jaccard_index: 0.4439 - loss: 0.2167 - val_accuracy: 0.9949 - val_dice_coef: 0.3705 - val_jaccard_index: 0.2483 - val_loss: 0.3343
Epoch 25/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 0.9964 - dice_coef: 0.5954 - jaccard_index: 0.4423 - loss: 0.2178
Epoch 25: val_dice_coef did not improve from 0.43285
191/191 ━━━━━━━━━━━━━━━━━━━━ 16s 82ms/step - accuracy: 0.9964 - dice_coef: 0.5955 - jaccard_index: 0.4424 - loss: 0.2178 - val_accuracy: 0.9941 - val_dice_coef: 0.4067 - val_jaccard_index: 0.2757 - val_loss: 0.3171
Epoch 26/100
189/191 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.9967 - dice_coef: 0.6196 - jaccard_index: 0.4672 - loss: 0.2051
Epoch 26: val_dice_coef did not improve from 0.43285
191/191 ━━━━━━━━━━━━━━━━━━━━ 16s 82ms/step - accuracy: 0.9967 - dice_coef: 0.6197 - jaccard_index: 0.4673 - loss: 0.2051 - val_accuracy: 0.9932 - val_dice_coef: 0.3883 - val_jaccard_index: 0.2541 - val_loss: 0.3289
Epoch 27/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.9966 - dice_coef: 0.6208 - jaccard_index: 0.4690 - loss: 0.2046
Epoch 27: val_dice_coef improved from 0.43285 to 0.43585, saving model to /mnt/c/Users/lejam/Desktop/CBIS-DDSM/manifest-1748122768688/best_mass_model.keras
191/191 ━━━━━━━━━━━━━━━━━━━━ 22s 117ms/step - accuracy: 0.9966 - dice_coef: 0.6208 - jaccard_index: 0.4690 - loss: 0.2045 - val_accuracy: 0.9937 - val_dice_coef: 0.4358 - val_jaccard_index: 0.2967 - val_loss: 0.3014
Epoch 28/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.9965 - dice_coef: 0.6038 - jaccard_index: 0.4498 - loss: 0.2130
Epoch 28: val_dice_coef did not improve from 0.43585
191/191 ━━━━━━━━━━━━━━━━━━━━ 16s 80ms/step - accuracy: 0.9965 - dice_coef: 0.6039 - jaccard_index: 0.4499 - loss: 0.2130 - val_accuracy: 0.9948 - val_dice_coef: 0.4221 - val_jaccard_index: 0.2882 - val_loss: 0.3084
Epoch 29/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.9967 - dice_coef: 0.6319 - jaccard_index: 0.4807 - loss: 0.1978
Epoch 29: val_dice_coef did not improve from 0.43585
191/191 ━━━━━━━━━━━━━━━━━━━━ 18s 93ms/step - accuracy: 0.9967 - dice_coef: 0.6319 - jaccard_index: 0.4807 - loss: 0.1978 - val_accuracy: 0.9946 - val_dice_coef: 0.4180 - val_jaccard_index: 0.2818 - val_loss: 0.3116
Epoch 30/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.9968 - dice_coef: 0.6287 - jaccard_index: 0.4764 - loss: 0.1996
Epoch 30: val_dice_coef did not improve from 0.43585
191/191 ━━━━━━━━━━━━━━━━━━━━ 15s 81ms/step - accuracy: 0.9968 - dice_coef: 0.6287 - jaccard_index: 0.4764 - loss: 0.1996 - val_accuracy: 0.9945 - val_dice_coef: 0.4012 - val_jaccard_index: 0.2654 - val_loss: 0.3182
Epoch 31/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.9969 - dice_coef: 0.6414 - jaccard_index: 0.4905 - loss: 0.1927
Epoch 31: val_dice_coef did not improve from 0.43585
191/191 ━━━━━━━━━━━━━━━━━━━━ 18s 94ms/step - accuracy: 0.9969 - dice_coef: 0.6415 - jaccard_index: 0.4906 - loss: 0.1927 - val_accuracy: 0.9948 - val_dice_coef: 0.3909 - val_jaccard_index: 0.2609 - val_loss: 0.3218
Epoch 32/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.9971 - dice_coef: 0.6628 - jaccard_index: 0.5128 - loss: 0.1817
Epoch 32: val_dice_coef did not improve from 0.43585
191/191 ━━━━━━━━━━━━━━━━━━━━ 15s 81ms/step - accuracy: 0.9971 - dice_coef: 0.6628 - jaccard_index: 0.5129 - loss: 0.1817 - val_accuracy: 0.9952 - val_dice_coef: 0.3922 - val_jaccard_index: 0.2633 - val_loss: 0.3219
Epoch 33/100
186/191 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.9972 - dice_coef: 0.6722 - jaccard_index: 0.5228 - loss: 0.1763
Epoch 33: val_dice_coef did not improve from 0.43585
191/191 ━━━━━━━━━━━━━━━━━━━━ 16s 81ms/step - accuracy: 0.9972 - dice_coef: 0.6722 - jaccard_index: 0.5228 - loss: 0.1763 - val_accuracy: 0.9950 - val_dice_coef: 0.4017 - val_jaccard_index: 0.2694 - val_loss: 0.3160
Epoch 34/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - accuracy: 0.9972 - dice_coef: 0.6773 - jaccard_index: 0.5296 - loss: 0.1740
Epoch 34: val_dice_coef did not improve from 0.43585
191/191 ━━━━━━━━━━━━━━━━━━━━ 18s 93ms/step - accuracy: 0.9972 - dice_coef: 0.6773 - jaccard_index: 0.5297 - loss: 0.1740 - val_accuracy: 0.9942 - val_dice_coef: 0.3830 - val_jaccard_index: 0.2539 - val_loss: 0.3269
Epoch 35/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.9971 - dice_coef: 0.6570 - jaccard_index: 0.5068 - loss: 0.1844
Epoch 35: val_dice_coef did not improve from 0.43585
191/191 ━━━━━━━━━━━━━━━━━━━━ 15s 80ms/step - accuracy: 0.9971 - dice_coef: 0.6571 - jaccard_index: 0.5069 - loss: 0.1844 - val_accuracy: 0.9952 - val_dice_coef: 0.3775 - val_jaccard_index: 0.2543 - val_loss: 0.3286
Epoch 36/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - accuracy: 0.9973 - dice_coef: 0.6871 - jaccard_index: 0.5407 - loss: 0.1682
Epoch 36: val_dice_coef did not improve from 0.43585
191/191 ━━━━━━━━━━━━━━━━━━━━ 18s 93ms/step - accuracy: 0.9973 - dice_coef: 0.6871 - jaccard_index: 0.5407 - loss: 0.1682 - val_accuracy: 0.9944 - val_dice_coef: 0.3792 - val_jaccard_index: 0.2525 - val_loss: 0.3287
Epoch 37/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.9973 - dice_coef: 0.6814 - jaccard_index: 0.5339 - loss: 0.1714
Epoch 37: val_dice_coef did not improve from 0.43585
191/191 ━━━━━━━━━━━━━━━━━━━━ 16s 81ms/step - accuracy: 0.9973 - dice_coef: 0.6814 - jaccard_index: 0.5339 - loss: 0.1714 - val_accuracy: 0.9950 - val_dice_coef: 0.3972 - val_jaccard_index: 0.2681 - val_loss: 0.3184
Epoch 38/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 0.9976 - dice_coef: 0.7069 - jaccard_index: 0.5654 - loss: 0.1580
Epoch 38: val_dice_coef did not improve from 0.43585
191/191 ━━━━━━━━━━━━━━━━━━━━ 18s 95ms/step - accuracy: 0.9976 - dice_coef: 0.7069 - jaccard_index: 0.5654 - loss: 0.1579 - val_accuracy: 0.9950 - val_dice_coef: 0.3704 - val_jaccard_index: 0.2461 - val_loss: 0.3327
Epoch 39/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.9977 - dice_coef: 0.7145 - jaccard_index: 0.5745 - loss: 0.1538
Epoch 39: val_dice_coef did not improve from 0.43585
191/191 ━━━━━━━━━━━━━━━━━━━━ 15s 81ms/step - accuracy: 0.9977 - dice_coef: 0.7145 - jaccard_index: 0.5744 - loss: 0.1538 - val_accuracy: 0.9949 - val_dice_coef: 0.3895 - val_jaccard_index: 0.2625 - val_loss: 0.3259
Epoch 40/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.9972 - dice_coef: 0.6708 - jaccard_index: 0.5243 - loss: 0.1771
Epoch 40: val_dice_coef did not improve from 0.43585
191/191 ━━━━━━━━━━━━━━━━━━━━ 19s 98ms/step - accuracy: 0.9972 - dice_coef: 0.6708 - jaccard_index: 0.5243 - loss: 0.1770 - val_accuracy: 0.9949 - val_dice_coef: 0.3710 - val_jaccard_index: 0.2458 - val_loss: 0.3315
Epoch 41/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.9976 - dice_coef: 0.7096 - jaccard_index: 0.5674 - loss: 0.1563
Epoch 41: val_dice_coef did not improve from 0.43585
191/191 ━━━━━━━━━━━━━━━━━━━━ 15s 80ms/step - accuracy: 0.9976 - dice_coef: 0.7097 - jaccard_index: 0.5675 - loss: 0.1562 - val_accuracy: 0.9951 - val_dice_coef: 0.3466 - val_jaccard_index: 0.2301 - val_loss: 0.3449
Epoch 42/100
186/191 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.9978 - dice_coef: 0.7273 - jaccard_index: 0.5873 - loss: 0.1469
Epoch 42: val_dice_coef did not improve from 0.43585
191/191 ━━━━━━━━━━━━━━━━━━━━ 16s 82ms/step - accuracy: 0.9978 - dice_coef: 0.7274 - jaccard_index: 0.5874 - loss: 0.1468 - val_accuracy: 0.9949 - val_dice_coef: 0.3192 - val_jaccard_index: 0.2059 - val_loss: 0.3591
Epoch 43/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - accuracy: 0.9977 - dice_coef: 0.7215 - jaccard_index: 0.5793 - loss: 0.1500
Epoch 43: val_dice_coef did not improve from 0.43585
191/191 ━━━━━━━━━━━━━━━━━━━━ 18s 93ms/step - accuracy: 0.9977 - dice_coef: 0.7215 - jaccard_index: 0.5794 - loss: 0.1500 - val_accuracy: 0.9951 - val_dice_coef: 0.3700 - val_jaccard_index: 0.2443 - val_loss: 0.3320
Epoch 44/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.9978 - dice_coef: 0.7357 - jaccard_index: 0.5974 - loss: 0.1425
Epoch 44: val_dice_coef did not improve from 0.43585
191/191 ━━━━━━━━━━━━━━━━━━━━ 15s 80ms/step - accuracy: 0.9978 - dice_coef: 0.7358 - jaccard_index: 0.5974 - loss: 0.1425 - val_accuracy: 0.9948 - val_dice_coef: 0.3733 - val_jaccard_index: 0.2480 - val_loss: 0.3314
Epoch 45/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.9979 - dice_coef: 0.7455 - jaccard_index: 0.6094 - loss: 0.1373
Epoch 45: val_dice_coef did not improve from 0.43585
191/191 ━━━━━━━━━━━━━━━━━━━━ 18s 94ms/step - accuracy: 0.9979 - dice_coef: 0.7455 - jaccard_index: 0.6094 - loss: 0.1373 - val_accuracy: 0.9946 - val_dice_coef: 0.3746 - val_jaccard_index: 0.2510 - val_loss: 0.3307
Epoch 46/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.9979 - dice_coef: 0.7382 - jaccard_index: 0.5997 - loss: 0.1413
Epoch 46: val_dice_coef did not improve from 0.43585
191/191 ━━━━━━━━━━━━━━━━━━━━ 15s 80ms/step - accuracy: 0.9979 - dice_coef: 0.7382 - jaccard_index: 0.5997 - loss: 0.1413 - val_accuracy: 0.9948 - val_dice_coef: 0.3746 - val_jaccard_index: 0.2457 - val_loss: 0.3319
Epoch 47/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 0.9980 - dice_coef: 0.7520 - jaccard_index: 0.6181 - loss: 0.1338
Epoch 47: val_dice_coef did not improve from 0.43585
191/191 ━━━━━━━━━━━━━━━━━━━━ 18s 95ms/step - accuracy: 0.9980 - dice_coef: 0.7520 - jaccard_index: 0.6181 - loss: 0.1338 - val_accuracy: 0.9950 - val_dice_coef: 0.3726 - val_jaccard_index: 0.2442 - val_loss: 0.3311
Epoch 48/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 0.9980 - dice_coef: 0.7562 - jaccard_index: 0.6235 - loss: 0.1314
Epoch 48: val_dice_coef did not improve from 0.43585
191/191 ━━━━━━━━━━━━━━━━━━━━ 16s 82ms/step - accuracy: 0.9980 - dice_coef: 0.7562 - jaccard_index: 0.6236 - loss: 0.1314 - val_accuracy: 0.9952 - val_dice_coef: 0.3581 - val_jaccard_index: 0.2343 - val_loss: 0.3390
Epoch 49/100

2025-07-06 00:57:29.266397: W external/local_xla/xla/tsl/framework/bfc_allocator.cc:310] Allocator (GPU_0_bfc) ran out of memory trying to allocate 4.34GiB with freed_by_count=0. The caller indicates that this is not a failure, but this may mean that there could be performance gains if more memory were available.
2025-07-06 00:57:30.227206: E external/local_xla/xla/stream_executor/cuda/cuda_timer.cc:86] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
2025-07-06 00:57:30.545318: E external/local_xla/xla/stream_executor/cuda/cuda_timer.cc:86] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
2025-07-06 00:57:31.066883: W external/local_xla/xla/tsl/framework/bfc_allocator.cc:310] Allocator (GPU_0_bfc) ran out of memory trying to allocate 4.49GiB with freed_by_count=0. The caller indicates that this is not a failure, but this may mean that there could be performance gains if more memory were available.
2025-07-06 00:57:34.110533: W external/local_xla/xla/tsl/framework/bfc_allocator.cc:310] Allocator (GPU_0_bfc) ran out of memory trying to allocate 4.32GiB with freed_by_count=0. The caller indicates that this is not a failure, but this may mean that there could be performance gains if more memory were available.

191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 189ms/step - accuracy: 0.9995 - dice_coef: 0.9350 - jaccard_index: 0.9013 - loss: 0.0342

2025-07-06 00:57:46.593102: W external/local_xla/xla/tsl/framework/bfc_allocator.cc:310] Allocator (GPU_0_bfc) ran out of memory trying to allocate 4.29GiB with freed_by_count=0. The caller indicates that this is not a failure, but this may mean that there could be performance gains if more memory were available.
2025-07-06 00:57:47.333183: E external/local_xla/xla/stream_executor/cuda/cuda_timer.cc:86] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
2025-07-06 00:57:47.503329: E external/local_xla/xla/stream_executor/cuda/cuda_timer.cc:86] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.

Epoch 1: val_dice_coef improved from 0.95847 to 0.96013, saving model to /mnt/c/Users/lejam/Desktop/CBIS-DDSM/manifest-1748122768688/best_mass_model.keras
191/191 ━━━━━━━━━━━━━━━━━━━━ 48s 250ms/step - accuracy: 0.9995 - dice_coef: 0.9350 - jaccard_index: 0.9013 - loss: 0.0342 - val_accuracy: 0.9996 - val_dice_coef: 0.9601 - val_jaccard_index: 0.9268 - val_loss: 0.0222
Epoch 2/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 0.9994 - dice_coef: 0.9290 - jaccard_index: 0.8881 - loss: 0.0375
Epoch 2: val_dice_coef did not improve from 0.96013
191/191 ━━━━━━━━━━━━━━━━━━━━ 17s 89ms/step - accuracy: 0.9994 - dice_coef: 0.9291 - jaccard_index: 0.8882 - loss: 0.0375 - val_accuracy: 0.9996 - val_dice_coef: 0.9554 - val_jaccard_index: 0.9184 - val_loss: 0.0254
Epoch 3/100
174/191 ━━━━━━━━━━━━━━━━━━━━ 1s 98ms/step - accuracy: 0.9994 - dice_coef: 0.9280 - jaccard_index: 0.8861 - loss: 0.0379
Epoch 3: val_dice_coef did not improve from 0.96013
191/191 ━━━━━━━━━━━━━━━━━━━━ 17s 88ms/step - accuracy: 0.9994 - dice_coef: 0.9294 - jaccard_index: 0.8881 - loss: 0.0371 - val_accuracy: 0.9995 - val_dice_coef: 0.9546 - val_jaccard_index: 0.9176 - val_loss: 0.0256
Epoch 4/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.9994 - dice_coef: 0.9369 - jaccard_index: 0.8997 - loss: 0.0332
Epoch 4: val_dice_coef did not improve from 0.96013
191/191 ━━━━━━━━━━━━━━━━━━━━ 19s 101ms/step - accuracy: 0.9994 - dice_coef: 0.9370 - jaccard_index: 0.8998 - loss: 0.0331 - val_accuracy: 0.9995 - val_dice_coef: 0.9531 - val_jaccard_index: 0.9157 - val_loss: 0.0265
Epoch 5/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.9995 - dice_coef: 0.9393 - jaccard_index: 0.9034 - loss: 0.0319
Epoch 5: val_dice_coef did not improve from 0.96013
191/191 ━━━━━━━━━━━━━━━━━━━━ 17s 87ms/step - accuracy: 0.9995 - dice_coef: 0.9394 - jaccard_index: 0.9035 - loss: 0.0319 - val_accuracy: 0.9995 - val_dice_coef: 0.9510 - val_jaccard_index: 0.9123 - val_loss: 0.0278
Epoch 6/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.9995 - dice_coef: 0.9413 - jaccard_index: 0.9070 - loss: 0.0306
Epoch 6: val_dice_coef did not improve from 0.96013
191/191 ━━━━━━━━━━━━━━━━━━━━ 19s 100ms/step - accuracy: 0.9995 - dice_coef: 0.9414 - jaccard_index: 0.9071 - loss: 0.0305 - val_accuracy: 0.9995 - val_dice_coef: 0.9506 - val_jaccard_index: 0.9119 - val_loss: 0.0280
Epoch 7/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.9995 - dice_coef: 0.9433 - jaccard_index: 0.9105 - loss: 0.0297
Epoch 7: val_dice_coef did not improve from 0.96013
191/191 ━━━━━━━━━━━━━━━━━━━━ 17s 87ms/step - accuracy: 0.9995 - dice_coef: 0.9434 - jaccard_index: 0.9105 - loss: 0.0297 - val_accuracy: 0.9995 - val_dice_coef: 0.9512 - val_jaccard_index: 0.9126 - val_loss: 0.0276
Epoch 8/100
185/191 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.9995 - dice_coef: 0.9436 - jaccard_index: 0.9111 - loss: 0.0295
Epoch 8: val_dice_coef did not improve from 0.96013
191/191 ━━━━━━━━━━━━━━━━━━━━ 17s 87ms/step - accuracy: 0.9995 - dice_coef: 0.9440 - jaccard_index: 0.9116 - loss: 0.0293 - val_accuracy: 0.9995 - val_dice_coef: 0.9491 - val_jaccard_index: 0.9088 - val_loss: 0.0280
Epoch 9/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.9995 - dice_coef: 0.9450 - jaccard_index: 0.9133 - loss: 0.0288
Epoch 9: val_dice_coef did not improve from 0.96013
191/191 ━━━━━━━━━━━━━━━━━━━━ 18s 97ms/step - accuracy: 0.9995 - dice_coef: 0.9450 - jaccard_index: 0.9134 - loss: 0.0288 - val_accuracy: 0.9995 - val_dice_coef: 0.9510 - val_jaccard_index: 0.9125 - val_loss: 0.0275
Epoch 10/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.9995 - dice_coef: 0.9451 - jaccard_index: 0.9140 - loss: 0.0287
Epoch 10: val_dice_coef did not improve from 0.96013
191/191 ━━━━━━━━━━━━━━━━━━━━ 16s 83ms/step - accuracy: 0.9995 - dice_coef: 0.9451 - jaccard_index: 0.9140 - loss: 0.0287 - val_accuracy: 0.9995 - val_dice_coef: 0.9498 - val_jaccard_index: 0.9105 - val_loss: 0.0281
Epoch 11/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.9995 - dice_coef: 0.9440 - jaccard_index: 0.9119 - loss: 0.0294
Epoch 11: val_dice_coef did not improve from 0.96013
191/191 ━━━━━━━━━━━━━━━━━━━━ 19s 97ms/step - accuracy: 0.9995 - dice_coef: 0.9441 - jaccard_index: 0.9120 - loss: 0.0294 - val_accuracy: 0.9995 - val_dice_coef: 0.9498 - val_jaccard_index: 0.9106 - val_loss: 0.0281
Epoch 12/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.9995 - dice_coef: 0.9441 - jaccard_index: 0.9123 - loss: 0.0292
Epoch 12: val_dice_coef did not improve from 0.96013
191/191 ━━━━━━━━━━━━━━━━━━━━ 16s 84ms/step - accuracy: 0.9995 - dice_coef: 0.9442 - jaccard_index: 0.9124 - loss: 0.0292 - val_accuracy: 0.9995 - val_dice_coef: 0.9504 - val_jaccard_index: 0.9116 - val_loss: 0.0278
Epoch 13/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.9995 - dice_coef: 0.9460 - jaccard_index: 0.9153 - loss: 0.0282
Epoch 13: val_dice_coef did not improve from 0.96013
191/191 ━━━━━━━━━━━━━━━━━━━━ 19s 100ms/step - accuracy: 0.9995 - dice_coef: 0.9460 - jaccard_index: 0.9153 - loss: 0.0282 - val_accuracy: 0.9995 - val_dice_coef: 0.9480 - val_jaccard_index: 0.9072 - val_loss: 0.0287
Epoch 14/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.9995 - dice_coef: 0.9462 - jaccard_index: 0.9156 - loss: 0.0281
Epoch 14: val_dice_coef did not improve from 0.96013
191/191 ━━━━━━━━━━━━━━━━━━━━ 16s 85ms/step - accuracy: 0.9995 - dice_coef: 0.9462 - jaccard_index: 0.9157 - loss: 0.0281 - val_accuracy: 0.9995 - val_dice_coef: 0.9494 - val_jaccard_index: 0.9098 - val_loss: 0.0284
Epoch 15/100
173/191 ━━━━━━━━━━━━━━━━━━━━ 1s 96ms/step - accuracy: 0.9995 - dice_coef: 0.9453 - jaccard_index: 0.9144 - loss: 0.0285
Epoch 15: val_dice_coef did not improve from 0.96013
191/191 ━━━━━━━━━━━━━━━━━━━━ 16s 85ms/step - accuracy: 0.9995 - dice_coef: 0.9463 - jaccard_index: 0.9158 - loss: 0.0280 - val_accuracy: 0.9995 - val_dice_coef: 0.9477 - val_jaccard_index: 0.9068 - val_loss: 0.0291
Epoch 16/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.9995 - dice_coef: 0.9464 - jaccard_index: 0.9159 - loss: 0.0280
Epoch 16: val_dice_coef did not improve from 0.96013
191/191 ━━━━━━━━━━━━━━━━━━━━ 19s 97ms/step - accuracy: 0.9995 - dice_coef: 0.9464 - jaccard_index: 0.9160 - loss: 0.0279 - val_accuracy: 0.9994 - val_dice_coef: 0.9462 - val_jaccard_index: 0.9041 - val_loss: 0.0298
Epoch 17/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.9995 - dice_coef: 0.9463 - jaccard_index: 0.9158 - loss: 0.0280
Epoch 17: val_dice_coef did not improve from 0.96013
191/191 ━━━━━━━━━━━━━━━━━━━━ 16s 85ms/step - accuracy: 0.9995 - dice_coef: 0.9464 - jaccard_index: 0.9158 - loss: 0.0279 - val_accuracy: 0.9995 - val_dice_coef: 0.9477 - val_jaccard_index: 0.9069 - val_loss: 0.0292
Epoch 18/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.9995 - dice_coef: 0.9461 - jaccard_index: 0.9154 - loss: 0.0281
Epoch 18: val_dice_coef did not improve from 0.96013
191/191 ━━━━━━━━━━━━━━━━━━━━ 19s 97ms/step - accuracy: 0.9995 - dice_coef: 0.9462 - jaccard_index: 0.9155 - loss: 0.0281 - val_accuracy: 0.9994 - val_dice_coef: 0.9456 - val_jaccard_index: 0.9031 - val_loss: 0.0298
Epoch 19/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.9995 - dice_coef: 0.9450 - jaccard_index: 0.9133 - loss: 0.0287
Epoch 19: val_dice_coef did not improve from 0.96013
191/191 ━━━━━━━━━━━━━━━━━━━━ 16s 84ms/step - accuracy: 0.9995 - dice_coef: 0.9451 - jaccard_index: 0.9134 - loss: 0.0287 - val_accuracy: 0.9994 - val_dice_coef: 0.9453 - val_jaccard_index: 0.9025 - val_loss: 0.0303
Epoch 20/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.9995 - dice_coef: 0.9435 - jaccard_index: 0.9106 - loss: 0.0297
Epoch 20: val_dice_coef did not improve from 0.96013
191/191 ━━━━━━━━━━━━━━━━━━━━ 19s 98ms/step - accuracy: 0.9995 - dice_coef: 0.9436 - jaccard_index: 0.9106 - loss: 0.0297 - val_accuracy: 0.9994 - val_dice_coef: 0.9454 - val_jaccard_index: 0.9023 - val_loss: 0.0305
Epoch 21/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.9994 - dice_coef: 0.9389 - jaccard_index: 0.9022 - loss: 0.0322
Epoch 21: val_dice_coef did not improve from 0.96013
191/191 ━━━━━━━━━━━━━━━━━━━━ 16s 83ms/step - accuracy: 0.9994 - dice_coef: 0.9390 - jaccard_index: 0.9023 - loss: 0.0322 - val_accuracy: 0.9994 - val_dice_coef: 0.9413 - val_jaccard_index: 0.8955 - val_loss: 0.0326
Epoch 22/100
165/191 ━━━━━━━━━━━━━━━━━━━━ 2s 95ms/step - accuracy: 0.9994 - dice_coef: 0.9310 - jaccard_index: 0.8892 - loss: 0.0367
Epoch 22: val_dice_coef did not improve from 0.96013
191/191 ━━━━━━━━━━━━━━━━━━━━ 16s 84ms/step - accuracy: 0.9994 - dice_coef: 0.9329 - jaccard_index: 0.8918 - loss: 0.0357 - val_accuracy: 0.9994 - val_dice_coef: 0.9441 - val_jaccard_index: 0.9003 - val_loss: 0.0310
Epoch 23/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.9995 - dice_coef: 0.9417 - jaccard_index: 0.9081 - loss: 0.0306
Epoch 23: val_dice_coef did not improve from 0.96013
191/191 ━━━━━━━━━━━━━━━━━━━━ 19s 97ms/step - accuracy: 0.9995 - dice_coef: 0.9417 - jaccard_index: 0.9082 - loss: 0.0306 - val_accuracy: 0.9994 - val_dice_coef: 0.9454 - val_jaccard_index: 0.9029 - val_loss: 0.0306
Epoch 24/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.9995 - dice_coef: 0.9420 - jaccard_index: 0.9085 - loss: 0.0304
Epoch 24: val_dice_coef did not improve from 0.96013
191/191 ━━━━━━━━━━━━━━━━━━━━ 16s 84ms/step - accuracy: 0.9995 - dice_coef: 0.9420 - jaccard_index: 0.9086 - loss: 0.0304 - val_accuracy: 0.9994 - val_dice_coef: 0.9453 - val_jaccard_index: 0.9023 - val_loss: 0.0308
Epoch 25/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.9995 - dice_coef: 0.9445 - jaccard_index: 0.9124 - loss: 0.0291
Epoch 25: val_dice_coef did not improve from 0.96013
191/191 ━━━━━━━━━━━━━━━━━━━━ 19s 97ms/step - accuracy: 0.9995 - dice_coef: 0.9446 - jaccard_index: 0.9125 - loss: 0.0290 - val_accuracy: 0.9994 - val_dice_coef: 0.9437 - val_jaccard_index: 0.8996 - val_loss: 0.0316
Epoch 26/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.9995 - dice_coef: 0.9457 - jaccard_index: 0.9145 - loss: 0.0284
Epoch 26: val_dice_coef did not improve from 0.96013
191/191 ━━━━━━━━━━━━━━━━━━━━ 16s 84ms/step - accuracy: 0.9995 - dice_coef: 0.9457 - jaccard_index: 0.9146 - loss: 0.0284 - val_accuracy: 0.9994 - val_dice_coef: 0.9458 - val_jaccard_index: 0.9035 - val_loss: 0.0304
Epoch 27/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.9995 - dice_coef: 0.9461 - jaccard_index: 0.9153 - loss: 0.0282
Epoch 27: val_dice_coef did not improve from 0.96013
191/191 ━━━━━━━━━━━━━━━━━━━━ 19s 99ms/step - accuracy: 0.9995 - dice_coef: 0.9461 - jaccard_index: 0.9153 - loss: 0.0282 - val_accuracy: 0.9994 - val_dice_coef: 0.9460 - val_jaccard_index: 0.9040 - val_loss: 0.0303
Epoch 28/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.9995 - dice_coef: 0.9461 - jaccard_index: 0.9154 - loss: 0.0281
Epoch 28: val_dice_coef did not improve from 0.96013
191/191 ━━━━━━━━━━━━━━━━━━━━ 16s 86ms/step - accuracy: 0.9995 - dice_coef: 0.9462 - jaccard_index: 0.9154 - loss: 0.0281 - val_accuracy: 0.9994 - val_dice_coef: 0.9446 - val_jaccard_index: 0.9015 - val_loss: 0.0309
Epoch 29/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.9995 - dice_coef: 0.9462 - jaccard_index: 0.9156 - loss: 0.0280
Epoch 29: val_dice_coef did not improve from 0.96013
191/191 ━━━━━━━━━━━━━━━━━━━━ 16s 84ms/step - accuracy: 0.9995 - dice_coef: 0.9463 - jaccard_index: 0.9157 - loss: 0.0280 - val_accuracy: 0.9994 - val_dice_coef: 0.9449 - val_jaccard_index: 0.9020 - val_loss: 0.0304
Epoch 30/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.9995 - dice_coef: 0.9465 - jaccard_index: 0.9160 - loss: 0.0279
Epoch 30: val_dice_coef did not improve from 0.96013
191/191 ━━━━━━━━━━━━━━━━━━━━ 19s 98ms/step - accuracy: 0.9995 - dice_coef: 0.9465 - jaccard_index: 0.9161 - loss: 0.0279 - val_accuracy: 0.9994 - val_dice_coef: 0.9443 - val_jaccard_index: 0.9011 - val_loss: 0.0306
Epoch 31/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.9995 - dice_coef: 0.9464 - jaccard_index: 0.9159 - loss: 0.0279
Epoch 31: val_dice_coef did not improve from 0.96013
191/191 ━━━━━━━━━━━━━━━━━━━━ 16s 84ms/step - accuracy: 0.9995 - dice_coef: 0.9465 - jaccard_index: 0.9160 - loss: 0.0279 - val_accuracy: 0.9994 - val_dice_coef: 0.9453 - val_jaccard_index: 0.9027 - val_loss: 0.0303
Epoch 32/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.9995 - dice_coef: 0.9465 - jaccard_index: 0.9159 - loss: 0.0279
Epoch 32: val_dice_coef did not improve from 0.96013
191/191 ━━━━━━━━━━━━━━━━━━━━ 19s 99ms/step - accuracy: 0.9995 - dice_coef: 0.9466 - jaccard_index: 0.9159 - loss: 0.0279 - val_accuracy: 0.9994 - val_dice_coef: 0.9444 - val_jaccard_index: 0.9013 - val_loss: 0.0310
Epoch 33/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.9995 - dice_coef: 0.9465 - jaccard_index: 0.9158 - loss: 0.0279
Epoch 33: val_dice_coef did not improve from 0.96013
191/191 ━━━━━━━━━━━━━━━━━━━━ 16s 84ms/step - accuracy: 0.9995 - dice_coef: 0.9465 - jaccard_index: 0.9158 - loss: 0.0279 - val_accuracy: 0.9994 - val_dice_coef: 0.9454 - val_jaccard_index: 0.9028 - val_loss: 0.0305
Epoch 34/100
188/191 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.9995 - dice_coef: 0.9464 - jaccard_index: 0.9157 - loss: 0.0279
Epoch 34: val_dice_coef did not improve from 0.96013
191/191 ━━━━━━━━━━━━━━━━━━━━ 16s 85ms/step - accuracy: 0.9995 - dice_coef: 0.9466 - jaccard_index: 0.9160 - loss: 0.0278 - val_accuracy: 0.9994 - val_dice_coef: 0.9452 - val_jaccard_index: 0.9023 - val_loss: 0.0302
Epoch 35/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.9995 - dice_coef: 0.9466 - jaccard_index: 0.9159 - loss: 0.0278
Epoch 35: val_dice_coef did not improve from 0.96013
191/191 ━━━━━━━━━━━━━━━━━━━━ 19s 97ms/step - accuracy: 0.9995 - dice_coef: 0.9466 - jaccard_index: 0.9160 - loss: 0.0278 - val_accuracy: 0.9994 - val_dice_coef: 0.9443 - val_jaccard_index: 0.9007 - val_loss: 0.0310
Epoch 36/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.9995 - dice_coef: 0.9463 - jaccard_index: 0.9154 - loss: 0.0280
Epoch 36: val_dice_coef did not improve from 0.96013
191/191 ━━━━━━━━━━━━━━━━━━━━ 16s 83ms/step - accuracy: 0.9995 - dice_coef: 0.9463 - jaccard_index: 0.9154 - loss: 0.0280 - val_accuracy: 0.9994 - val_dice_coef: 0.9435 - val_jaccard_index: 0.8992 - val_loss: 0.0313
Epoch 37/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.9995 - dice_coef: 0.9455 - jaccard_index: 0.9140 - loss: 0.0285
Epoch 37: val_dice_coef did not improve from 0.96013
191/191 ━━━━━━━━━━━━━━━━━━━━ 19s 98ms/step - accuracy: 0.9995 - dice_coef: 0.9456 - jaccard_index: 0.9141 - loss: 0.0285 - val_accuracy: 0.9994 - val_dice_coef: 0.9405 - val_jaccard_index: 0.8944 - val_loss: 0.0328
Epoch 38/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.9995 - dice_coef: 0.9447 - jaccard_index: 0.9124 - loss: 0.0290
Epoch 38: val_dice_coef did not improve from 0.96013
191/191 ━━━━━━━━━━━━━━━━━━━━ 16s 84ms/step - accuracy: 0.9995 - dice_coef: 0.9447 - jaccard_index: 0.9124 - loss: 0.0290 - val_accuracy: 0.9994 - val_dice_coef: 0.9432 - val_jaccard_index: 0.8989 - val_loss: 0.0315
Epoch 39/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.9995 - dice_coef: 0.9446 - jaccard_index: 0.9123 - loss: 0.0290
Epoch 39: val_dice_coef did not improve from 0.96013
191/191 ━━━━━━━━━━━━━━━━━━━━ 19s 99ms/step - accuracy: 0.9995 - dice_coef: 0.9446 - jaccard_index: 0.9123 - loss: 0.0290 - val_accuracy: 0.9994 - val_dice_coef: 0.9430 - val_jaccard_index: 0.8986 - val_loss: 0.0321
Epoch 40/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.9995 - dice_coef: 0.9447 - jaccard_index: 0.9124 - loss: 0.0290
Epoch 40: val_dice_coef did not improve from 0.96013
191/191 ━━━━━━━━━━━━━━━━━━━━ 16s 85ms/step - accuracy: 0.9995 - dice_coef: 0.9447 - jaccard_index: 0.9125 - loss: 0.0290 - val_accuracy: 0.9994 - val_dice_coef: 0.9428 - val_jaccard_index: 0.8981 - val_loss: 0.0319
Epoch 41/100
171/191 ━━━━━━━━━━━━━━━━━━━━ 1s 96ms/step - accuracy: 0.9995 - dice_coef: 0.9441 - jaccard_index: 0.9118 - loss: 0.0292
Epoch 41: val_dice_coef did not improve from 0.96013
191/191 ━━━━━━━━━━━━━━━━━━━━ 16s 86ms/step - accuracy: 0.9995 - dice_coef: 0.9452 - jaccard_index: 0.9134 - loss: 0.0286 - val_accuracy: 0.9994 - val_dice_coef: 0.9424 - val_jaccard_index: 0.8975 - val_loss: 0.0315
Epoch 42/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.9995 - dice_coef: 0.9454 - jaccard_index: 0.9138 - loss: 0.0285
Epoch 42: val_dice_coef did not improve from 0.96013
191/191 ━━━━━━━━━━━━━━━━━━━━ 19s 99ms/step - accuracy: 0.9995 - dice_coef: 0.9455 - jaccard_index: 0.9138 - loss: 0.0285 - val_accuracy: 0.9994 - val_dice_coef: 0.9412 - val_jaccard_index: 0.8955 - val_loss: 0.0327
Epoch 43/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.9995 - dice_coef: 0.9454 - jaccard_index: 0.9137 - loss: 0.0285
Epoch 43: val_dice_coef did not improve from 0.96013
191/191 ━━━━━━━━━━━━━━━━━━━━ 16s 85ms/step - accuracy: 0.9995 - dice_coef: 0.9454 - jaccard_index: 0.9137 - loss: 0.0285 - val_accuracy: 0.9994 - val_dice_coef: 0.9419 - val_jaccard_index: 0.8968 - val_loss: 0.0328
Epoch 44/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.9995 - dice_coef: 0.9443 - jaccard_index: 0.9117 - loss: 0.0292
Epoch 44: val_dice_coef did not improve from 0.96013
191/191 ━━━━━━━━━━━━━━━━━━━━ 19s 99ms/step - accuracy: 0.9995 - dice_coef: 0.9444 - jaccard_index: 0.9117 - loss: 0.0291 - val_accuracy: 0.9993 - val_dice_coef: 0.9340 - val_jaccard_index: 0.8836 - val_loss: 0.0367
Epoch 45/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.9995 - dice_coef: 0.9450 - jaccard_index: 0.9131 - loss: 0.0287
Epoch 45: val_dice_coef did not improve from 0.96013
191/191 ━━━━━━━━━━━━━━━━━━━━ 16s 84ms/step - accuracy: 0.9995 - dice_coef: 0.9451 - jaccard_index: 0.9132 - loss: 0.0287 - val_accuracy: 0.9994 - val_dice_coef: 0.9428 - val_jaccard_index: 0.8983 - val_loss: 0.0320
Epoch 46/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.9995 - dice_coef: 0.9459 - jaccard_index: 0.9146 - loss: 0.0283
Epoch 46: val_dice_coef did not improve from 0.96013
191/191 ━━━━━━━━━━━━━━━━━━━━ 19s 99ms/step - accuracy: 0.9995 - dice_coef: 0.9459 - jaccard_index: 0.9147 - loss: 0.0283 - val_accuracy: 0.9994 - val_dice_coef: 0.9400 - val_jaccard_index: 0.8940 - val_loss: 0.0338
Epoch 47/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.9995 - dice_coef: 0.9461 - jaccard_index: 0.9150 - loss: 0.0281
Epoch 47: val_dice_coef did not improve from 0.96013
191/191 ━━━━━━━━━━━━━━━━━━━━ 16s 84ms/step - accuracy: 0.9995 - dice_coef: 0.9461 - jaccard_index: 0.9151 - loss: 0.0281 - val_accuracy: 0.9993 - val_dice_coef: 0.9376 - val_jaccard_index: 0.8899 - val_loss: 0.0344
Epoch 48/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.9995 - dice_coef: 0.9458 - jaccard_index: 0.9146 - loss: 0.0283
Epoch 48: val_dice_coef did not improve from 0.96013
191/191 ━━━━━━━━━━━━━━━━━━━━ 19s 98ms/step - accuracy: 0.9995 - dice_coef: 0.9459 - jaccard_index: 0.9146 - loss: 0.0282 - val_accuracy: 0.9994 - val_dice_coef: 0.9395 - val_jaccard_index: 0.8932 - val_loss: 0.0339
Epoch 49/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.9995 - dice_coef: 0.9461 - jaccard_index: 0.9151 - loss: 0.0281
Epoch 49: val_dice_coef did not improve from 0.96013
191/191 ━━━━━━━━━━━━━━━━━━━━ 15s 78ms/step - accuracy: 0.9995 - dice_coef: 0.9461 - jaccard_index: 0.9151 - loss: 0.0281 - val_accuracy: 0.9994 - val_dice_coef: 0.9411 - val_jaccard_index: 0.8951 - val_loss: 0.0324
Epoch 50/100
191/191 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.9995 - dice_coef: 0.9453 - jaccard_index: 0.9134 - loss: 0.0286
Epoch 50: val_dice_coef did not improve from 0.96013

### Save model

In [19]:
# Save the entire trained model to disk in the specified directory
model.save(os.path.join(DATA_ROOT, 'mass_model.keras'))

### Save history

In [20]:
# Convert each training history object in the 'history' list to a DataFrame
# Add a 'fold' column to identify which fold the history corresponds to
all_histories = []

for i, hist in enumerate(history):
    df = pd.DataFrame(hist.history)
    df['fold'] = i  # Mark the fold number
    all_histories.append(df)

# Concatenate all fold DataFrames into one DataFrame for easier analysis
hist_df = pd.concat(all_histories, ignore_index=True)

# Save the combined training histories to a CSV file for later inspection or plotting
hist_df.to_csv(os.path.join(DATA_ROOT, 'history.csv'), index=False)