In [1]:
# Display images
import os
import glob
import pydicom
import numpy as np
import pandas as pd

#pd.options.display.max_rows = 999
pd.set_option('display.max_colwidth', None)

In [2]:
#
# @brief A self-contained script to print project paths.
#
# This script attempts to import the 'Paths' class from 'Components.definitions'
# and print its attributes, which are expected to contain key project file paths.
# It includes robust error handling to notify the user if the module or
# its attributes are missing.
#
try:
    from Components.definitions import Paths
    print("Project Paths:")
    print(f"\tDataset root path: {Paths.root}")
    print(f"\tMetadata file path: {Paths.metadata_csv}")
    print(f"\tMass training data path: {Paths.new_mass_train_csv}")
    print(f"\tMass testing data path: {Paths.new_mass_test_csv}")
    print(f"\tMass training data path: {Paths.new_calc_train_csv}")
    print(f"\tMass testing data path: {Paths.new_calc_test_csv}")
except ImportError as ex:
    print(f"\nError: {ex}. Please check the import path 'Components.definitions' and the file 'definitions.py'.")
except AttributeError as e:
    print(f"\nMissing attribute in 'Paths' class: {e}. Please ensure all paths are correctly defined in 'definitions.py'.")

Project Paths:
	Dataset root path: /mnt/c/Users/lejam/Desktop/CBIS-DDSM/manifest-1748122768688
	Metadata file path: /mnt/c/Users/lejam/Desktop/CBIS-DDSM/manifest-1748122768688/metadata.csv
	Mass training data path: /mnt/c/Users/lejam/Desktop/CBIS-DDSM/manifest-1748122768688/new_mass_case_description_train_set.csv
	Mass testing data path: /mnt/c/Users/lejam/Desktop/CBIS-DDSM/manifest-1748122768688/new_mass_case_description_test_set.csv
	Mass training data path: /mnt/c/Users/lejam/Desktop/CBIS-DDSM/manifest-1748122768688/new_calc_case_description_train_set.csv
	Mass testing data path: /mnt/c/Users/lejam/Desktop/CBIS-DDSM/manifest-1748122768688/new_calc_case_description_test_set.csv

In [3]:
df_meta = pd.read_csv(Paths.metadata_csv)
print(df_meta.shape)
df_meta.head(3)

(6775, 17)

,Series UID,Collection,3rd Party Analysis,Data Description URI,Subject ID,Study UID,Study Description,Study Date,Series Description,Manufacturer,Modality,SOP Class Name,SOP Class UID,Number of Images,File Size,File Location,Download Timestamp
0,1.3.6.1.4.1.9590.100.1.2.374115997511889073021386151921807063992,CBIS-DDSM,NaN,https://doi.org/10.7937/K9/TCIA.2016.7O02S9CY,Calc-Test_P_00038_LEFT_CC,1.3.6.1.4.1.9590.100.1.2.85935434310203356712688695661986996009,NaN,08-29-2017,full mammogram images,NaN,MG,Secondary Capture Image Storage,1.2.840.10008.5.1.4.1.1.7,1,27.84 MB,.\CBIS-DDSM\Calc-Test_P_00038_LEFT_CC\08-29-2017-DDSM-NA-96009\1.000000-full mammogram images-63992,2025-05-24T22:44:39.334
1,1.3.6.1.4.1.9590.100.1.2.174390361112646747718661211471328897934,CBIS-DDSM,NaN,https://doi.org/10.7937/K9/TCIA.2016.7O02S9CY,Calc-Test_P_00038_LEFT_MLO,1.3.6.1.4.1.9590.100.1.2.384159464510350889125645400702639717613,NaN,08-29-2017,full mammogram images,NaN,MG,Secondary Capture Image Storage,1.2.840.10008.5.1.4.1.1.7,1,28.97 MB,.\CBIS-DDSM\Calc-Test_P_00038_LEFT_MLO\08-29-2017-DDSM-NA-17613\1.000000-full mammogram images-97934,2025-05-24T22:44:43.456
2,1.3.6.1.4.1.9590.100.1.2.188613955710170417803011787532523988680,CBIS-DDSM,NaN,https://doi.org/10.7937/K9/TCIA.2016.7O02S9CY,Calc-Test_P_00038_LEFT_MLO_1,1.3.6.1.4.1.9590.100.1.2.29112199613143138535387754440942211739,NaN,08-29-2017,ROI mask images,NaN,MG,Secondary Capture Image Storage,1.2.840.10008.5.1.4.1.1.7,2,14.62 MB,.\CBIS-DDSM\Calc-Test_P_00038_LEFT_MLO_1\08-29-2017-DDSM-NA-11739\1.000000-ROI mask images-88680,2025-05-24T22:44:44.687

In [4]:
# Load mass datasets
mass_train = pd.read_csv(Paths.mass_train_csv)
mass_test = pd.read_csv(Paths.mass_test_csv)

### Update image paths

In [5]:
from Components.image_utils import ImagePathUpdater

# Make a list of the image paths
cols = ['image file path', 'cropped image file path', 'ROI mask file path']

2025-08-17 14:10:36.868147: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-08-17 14:10:36.880646: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1755436236.893201   53858 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1755436236.897107   53858 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1755436236.908516   53858 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1755436236.908530   53858 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1755436236.908531   53858 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1755436236.908532   53858 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2025-08-17 14:10:36.912236: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

##### Training data

In [6]:
train_data_updater = ImagePathUpdater(df_meta, mass_train, cols[0], Paths.root)
train_data_updater.update()

In [7]:
train_data_updater = ImagePathUpdater(df_meta, mass_train, cols[1], Paths.root)
train_data_updater.update()

In [8]:
train_data_updater = ImagePathUpdater(df_meta, mass_train, cols[2], Paths.root)
train_data_updater.update()

In [9]:
# Save the updated data
mass_train.to_csv(Paths.new_mass_train_csv, index=False)

##### Test data

In [10]:
test_data_updater = ImagePathUpdater(df_meta, mass_test, cols[0], Paths.root)
test_data_updater.update()

In [11]:
test_data_updater = ImagePathUpdater(df_meta, mass_test, cols[1], Paths.root)
test_data_updater.update()

In [12]:
test_data_updater = ImagePathUpdater(df_meta, mass_test, cols[2], Paths.root)
test_data_updater.update()

In [13]:
# Save the updated data
mass_test.to_csv(Paths.new_mass_test_csv, index=False)

### Results

In [14]:
rst_cols = ['pathology'] + cols
rst_cols

['pathology',
 'image file path',
 'cropped image file path',
 'ROI mask file path']

In [15]:
mass_train[rst_cols].head(2)

,pathology,image file path,cropped image file path,ROI mask file path
0,MALIGNANT,Mass-Training_P_00001_LEFT_CC/07-20-2016-DDSM-NA-74994/1.000000-full mammogram images-24515/1-1.dcm,Mass-Training_P_00001_LEFT_CC_1/07-21-2016-DDSM-NA-39106/1.000000-ROI mask images-99650/1-2.dcm,Mass-Training_P_00001_LEFT_CC_1/07-21-2016-DDSM-NA-39106/1.000000-ROI mask images-99650/1-1.dcm
1,MALIGNANT,Mass-Training_P_00001_LEFT_MLO/07-20-2016-DDSM-NA-90988/1.000000-full mammogram images-80834/1-1.dcm,Mass-Training_P_00001_LEFT_MLO_1/07-21-2016-DDSM-NA-82526/1.000000-ROI mask images-86053/1-1.dcm,Mass-Training_P_00001_LEFT_MLO_1/07-21-2016-DDSM-NA-82526/1.000000-ROI mask images-86053/1-2.dcm

In [16]:
mass_train[rst_cols].tail(2)

,pathology,image file path,cropped image file path,ROI mask file path
1316,MALIGNANT,Mass-Training_P_02092_LEFT_CC/07-20-2016-DDSM-NA-80250/1.000000-full mammogram images-67422/1-1.dcm,Mass-Training_P_02092_LEFT_CC_1/07-20-2016-DDSM-NA-75288/1.000000-cropped images-03171/1-1.dcm,Mass-Training_P_02092_LEFT_CC_1/07-21-2016-DDSM-NA-18548/1.000000-ROI mask images-89402/1-1.dcm
1317,MALIGNANT,Mass-Training_P_02092_LEFT_MLO/07-20-2016-DDSM-NA-65216/1.000000-full mammogram images-91615/1-1.dcm,Mass-Training_P_02092_LEFT_MLO_1/07-20-2016-DDSM-NA-20213/1.000000-cropped images-58924/1-1.dcm,Mass-Training_P_02092_LEFT_MLO_1/07-21-2016-DDSM-NA-14412/1.000000-ROI mask images-30086/1-1.dcm

In [17]:
mass_test[cols].head(2)

,image file path,cropped image file path,ROI mask file path
0,Mass-Test_P_00016_LEFT_CC/10-04-2016-DDSM-NA-30104/1.000000-full mammogram images-14172/1-1.dcm,Mass-Test_P_00016_LEFT_CC_1/10-04-2016-DDSM-NA-09887/1.000000-cropped images-26184/1-2.dcm,Mass-Test_P_00016_LEFT_CC_1/10-04-2016-DDSM-NA-09887/1.000000-cropped images-26184/1-1.dcm
1,Mass-Test_P_00016_LEFT_MLO/10-04-2016-DDSM-NA-54392/1.000000-full mammogram images-35518/1-1.dcm,Mass-Test_P_00016_LEFT_MLO_1/10-04-2016-DDSM-NA-15563/1.000000-cropped images-77287/1-2.dcm,Mass-Test_P_00016_LEFT_MLO_1/10-04-2016-DDSM-NA-15563/1.000000-cropped images-77287/1-1.dcm

In [18]:
mass_test[cols].tail(2)

,image file path,cropped image file path,ROI mask file path
376,Mass-Test_P_01912_RIGHT_CC/10-04-2016-DDSM-NA-59644/1.000000-full mammogram images-23281/1-1.dcm,Mass-Test_P_01912_RIGHT_CC_1/10-04-2016-DDSM-NA-61275/1.000000-ROI mask images-45359/1-1.dcm,Mass-Test_P_01912_RIGHT_CC_1/10-04-2016-DDSM-NA-61275/1.000000-ROI mask images-45359/1-2.dcm
377,Mass-Test_P_01912_RIGHT_MLO/10-04-2016-DDSM-NA-46673/1.000000-full mammogram images-74983/1-1.dcm,Mass-Test_P_01912_RIGHT_MLO_1/10-04-2016-DDSM-NA-41042/1.000000-ROI mask images-74314/1-1.dcm,Mass-Test_P_01912_RIGHT_MLO_1/10-04-2016-DDSM-NA-41042/1.000000-ROI mask images-74314/1-2.dcm

### Evaluation

In [19]:
# Load mass datasets again
unchanged_mass_train = pd.read_csv(Paths.mass_train_csv)
unchanged_mass_test = pd.read_csv(Paths.mass_test_csv)

In [20]:
unchanged_mass_train[rst_cols].head(1)

,pathology,image file path,cropped image file path,ROI mask file path
0,MALIGNANT,Mass-Training_P_00001_LEFT_CC/1.3.6.1.4.1.9590.100.1.2.422112722213189649807611434612228974994/1.3.6.1.4.1.9590.100.1.2.342386194811267636608694132590482924515/000000.dcm,Mass-Training_P_00001_LEFT_CC_1/1.3.6.1.4.1.9590.100.1.2.108268213011361124203859148071588939106/1.3.6.1.4.1.9590.100.1.2.296736403313792599626368780122205399650/000000.dcm,Mass-Training_P_00001_LEFT_CC_1/1.3.6.1.4.1.9590.100.1.2.108268213011361124203859148071588939106/1.3.6.1.4.1.9590.100.1.2.296736403313792599626368780122205399650/000001.dcm\n

In [21]:
unchanged_mass_test[rst_cols].head(1)

,pathology,image file path,cropped image file path,ROI mask file path
0,MALIGNANT,Mass-Test_P_00016_LEFT_CC/1.3.6.1.4.1.9590.100.1.2.416403281812750683720028031170500130104/1.3.6.1.4.1.9590.100.1.2.245063149211255120613007755642780114172/000000.dcm,Mass-Test_P_00016_LEFT_CC_1/1.3.6.1.4.1.9590.100.1.2.259596319110047779433501728143778409887/1.3.6.1.4.1.9590.100.1.2.30820586311062570442302321942433426184/000000.dcm,Mass-Test_P_00016_LEFT_CC_1/1.3.6.1.4.1.9590.100.1.2.259596319110047779433501728143778409887/1.3.6.1.4.1.9590.100.1.2.30820586311062570442302321942433426184/000001.dcm\n

In [22]:
all_cols = list(unchanged_mass_train.columns)
print(f"columns: {all_cols} (size: {len(all_cols)})")

columns: ['patient_id', 'breast_density', 'left or right breast', 'image view', 'abnormality id', 'abnormality type', 'mass shape', 'mass margins', 'assessment', 'pathology', 'subtlety', 'image file path', 'cropped image file path', 'ROI mask file path'] (size: 14)

In [23]:
sliced_cols = list(unchanged_mass_train.columns)[:-3]
print(f"columns without paths: {sliced_cols} (size: {len(sliced_cols)})")

columns without paths: ['patient_id', 'breast_density', 'left or right breast', 'image view', 'abnormality id', 'abnormality type', 'mass shape', 'mass margins', 'assessment', 'pathology', 'subtlety'] (size: 11)

##### Compare values column-wise between datasets

In [24]:
# Training data
df_train = pd.merge(
    unchanged_mass_train.reset_index(), mass_train.reset_index(),
    how='outer', on=sliced_cols)
df_train.head(3)

,index_x,patient_id,breast_density,left or right breast,image view,abnormality id,abnormality type,mass shape,mass margins,assessment,pathology,subtlety,image file path_x,cropped image file path_x,ROI mask file path_x,index_y,image file path_y,cropped image file path_y,ROI mask file path_y
0,0,P_00001,3,LEFT,CC,1,mass,IRREGULAR-ARCHITECTURAL_DISTORTION,SPICULATED,4,MALIGNANT,4,Mass-Training_P_00001_LEFT_CC/1.3.6.1.4.1.9590.100.1.2.422112722213189649807611434612228974994/1.3.6.1.4.1.9590.100.1.2.342386194811267636608694132590482924515/000000.dcm,Mass-Training_P_00001_LEFT_CC_1/1.3.6.1.4.1.9590.100.1.2.108268213011361124203859148071588939106/1.3.6.1.4.1.9590.100.1.2.296736403313792599626368780122205399650/000000.dcm,Mass-Training_P_00001_LEFT_CC_1/1.3.6.1.4.1.9590.100.1.2.108268213011361124203859148071588939106/1.3.6.1.4.1.9590.100.1.2.296736403313792599626368780122205399650/000001.dcm\n,0,Mass-Training_P_00001_LEFT_CC/07-20-2016-DDSM-NA-74994/1.000000-full mammogram images-24515/1-1.dcm,Mass-Training_P_00001_LEFT_CC_1/07-21-2016-DDSM-NA-39106/1.000000-ROI mask images-99650/1-2.dcm,Mass-Training_P_00001_LEFT_CC_1/07-21-2016-DDSM-NA-39106/1.000000-ROI mask images-99650/1-1.dcm
1,1,P_00001,3,LEFT,MLO,1,mass,IRREGULAR-ARCHITECTURAL_DISTORTION,SPICULATED,4,MALIGNANT,4,Mass-Training_P_00001_LEFT_MLO/1.3.6.1.4.1.9590.100.1.2.319478999311971442426185353560182990988/1.3.6.1.4.1.9590.100.1.2.359308329312397897125630708681441180834/000000.dcm,Mass-Training_P_00001_LEFT_MLO_1/1.3.6.1.4.1.9590.100.1.2.188473874511440575807446266233629582526/1.3.6.1.4.1.9590.100.1.2.227955274711225756835838775062793186053/000000.dcm,Mass-Training_P_00001_LEFT_MLO_1/1.3.6.1.4.1.9590.100.1.2.188473874511440575807446266233629582526/1.3.6.1.4.1.9590.100.1.2.227955274711225756835838775062793186053/000001.dcm\n,1,Mass-Training_P_00001_LEFT_MLO/07-20-2016-DDSM-NA-90988/1.000000-full mammogram images-80834/1-1.dcm,Mass-Training_P_00001_LEFT_MLO_1/07-21-2016-DDSM-NA-82526/1.000000-ROI mask images-86053/1-1.dcm,Mass-Training_P_00001_LEFT_MLO_1/07-21-2016-DDSM-NA-82526/1.000000-ROI mask images-86053/1-2.dcm
2,2,P_00004,3,LEFT,CC,1,mass,ARCHITECTURAL_DISTORTION,ILL_DEFINED,4,BENIGN,3,Mass-Training_P_00004_LEFT_CC/1.3.6.1.4.1.9590.100.1.2.347107867812656628709864319310977895697/1.3.6.1.4.1.9590.100.1.2.89180046211022531834352631483669346540/000000.dcm,Mass-Training_P_00004_LEFT_CC_1/1.3.6.1.4.1.9590.100.1.2.414182170112396175925115449620455230167/1.3.6.1.4.1.9590.100.1.2.429120414011832984817094399141838850375/000000.dcm,Mass-Training_P_00004_LEFT_CC_1/1.3.6.1.4.1.9590.100.1.2.414182170112396175925115449620455230167/1.3.6.1.4.1.9590.100.1.2.429120414011832984817094399141838850375/000001.dcm\n,2,Mass-Training_P_00004_LEFT_CC/07-20-2016-DDSM-NA-95697/1.000000-full mammogram images-46540/1-1.dcm,Mass-Training_P_00004_LEFT_CC_1/07-21-2016-DDSM-NA-30167/1.000000-ROI mask images-50375/1-2.dcm,Mass-Training_P_00004_LEFT_CC_1/07-21-2016-DDSM-NA-30167/1.000000-ROI mask images-50375/1-1.dcm

In [25]:
# Compare two related columns
# The values in each column don't have to match exactly
df_train['image result'] = np.where(
    (df_train['image file path_x']==df_train['image file path_y']),
    True, False)

In [26]:
if False in list(df_train['image result'].unique()):
    print(f"[ TEST PASS ] All image file paths were successfully updated")
else:
    print(f"[ TEST FAIL ] Some image file paths do not match between the original and updated datasets")

[ TEST PASS ] All image file paths were successfully updated

In [27]:
# Compare two related columns
# The values in each column don't have to match exactly
df_train['cropped image result'] = np.where(
    (df_train['cropped image file path_x']==df_train['cropped image file path_y']),
    True, False)

In [28]:
if False in list(df_train['cropped image result'].unique()):
    print(f"[ TEST PASS ] All cropped image file paths were successfully updated")
else:
    print(f"[ TEST FAIL ] Some cropped image file paths do not match between the original and updated datasets")

[ TEST PASS ] All cropped image file paths were successfully updated

In [29]:
# Compare two related columns
# The values in each column don't have to match exactly
df_train['ROI mask result'] = np.where(
    (df_train['ROI mask file path_x']==df_train['ROI mask file path_y']),
    True, False)

In [30]:
if False in list(df_train['ROI mask result'].unique()):
    print(f"[ TEST PASS ] All ROI mask file paths were successfully updated")
else:
    print(f"[ TEST FAIL ] Some ROI mask file paths do not match between the original and updated datasets")

[ TEST PASS ] All ROI mask file paths were successfully updated

### Summary

The CBIS-DDSM dataset includes a Series Description column that indicates the image type, such as 'full mammogram images', 'ROI mask images', or 'cropped images'. However, some of these descriptions are incorrect. In particular, ROI mask images and cropped images are stored in the same folder, but their Series Descriptions are inconsistently labelled as either 'ROI mask images' or 'cropped images'. Each image should be accurately labelled, as this information is crucial for proper dataset preparation and effective model training.

To address this issue, an initial rule was applied in the Test_DataQuality.ipynb file: ROI mask images were identified as those containing only pixel values of 0 and 255 (i.e., strictly black and white), whereas cropped images contained a broader range of pixel values. This distinction allowed for reliable reclassification. Preliminary testing on a sample of images confirmed that this method effectively corrected the labels.

A more robust and permanent solution was also implemented here. The root cause of the problem was traced back to incorrect image path information in the original CSV files provided by the Cancer Imaging Archive. To resolve this, a custom class named ImagePathUpdater was developed to update the path information for full images, cropped images, and ROI masks.

After updating the paths, an evaluation was performed by comparing each updated column with its corresponding original column. Since the paths had been corrected, the values in each pair of related columns were expected to differ. All three comparisons for full images, cropped images, and ROI masks were successful, as demonstrated in the evaluation section of the code.